name: knighthood_heroes
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.0
  google_fonts: ^5.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

  # fonts
    - assets/fonts/troika.ttf

  # general
    - assets/images/skills/chance.png
    - assets/images/skills/damage.png
    - assets/images/skills/damageHeal.png
    - assets/images/skills/debuff.png
    - assets/images/skills/strongVs.png
    - assets/images/skills/restoreHealth.png
    - assets/images/skills/restoreArmor.png
    - assets/images/skills/fillsRage.png
    - assets/images/skills/harmsPlayer.png
    - assets/images/skills/delayPowers.png
    - assets/images/skills/leechHealth.png
    - assets/images/skills/leechHealthAll.png
    - assets/images/skills/damagePlayerTarget.png
    - assets/images/skills/damageOneBack.png
    - assets/images/skills/damageBackRow.png
    - assets/images/skills/damageFrontRow.png
    - assets/images/skills/damageEnemiesInFront.png
    - assets/images/skills/damageRandom.png
    - assets/images/skills/damageAll.png
    - assets/images/skills/damageSpread.png
    - assets/images/skills/ignoresArmor.png
    - assets/images/skills/dispelBuffs.png
    - assets/images/skills/dispelDebuffs.png
    - assets/images/skills/focus.png
    - assets/images/skills/none.png

  # heros avatars
    - assets/images/heroes/Aeron.jpeg
    - assets/images/heroes/Alder.jpeg
    - assets/images/heroes/Anaara.jpeg
    - assets/images/heroes/Ash.jpeg
    - assets/images/heroes/Ayako.jpeg
    - assets/images/heroes/Azhar.jpeg
    - assets/images/heroes/Balberith.jpeg
    - assets/images/heroes/Balendu.jpeg
    - assets/images/heroes/Bayani.jpeg
    - assets/images/heroes/Blaine.jpeg
    - assets/images/heroes/Brutus.jpeg
    - assets/images/heroes/Byrne.jpeg
    - assets/images/heroes/Caliban.jpeg
    - assets/images/heroes/Carmilla.jpeg
    - assets/images/heroes/Cladis.jpeg
    - assets/images/heroes/Delphinia.jpeg
    - assets/images/heroes/DonDiego.jpeg
    - assets/images/heroes/DoctorFlox.jpeg
    - assets/images/heroes/Dvalin.jpeg
    - assets/images/heroes/Eileen.jpeg
    - assets/images/heroes/Ericson.jpeg
    - assets/images/heroes/Erinn.jpeg
    - assets/images/heroes/Fahari.jpeg
    - assets/images/heroes/Garron.jpeg
    - assets/images/heroes/Geber.jpeg
    - assets/images/heroes/Grax.jpeg
    - assets/images/heroes/Grimm.jpeg
    - assets/images/heroes/Griz.jpeg
    - assets/images/heroes/Gunn.jpeg
    - assets/images/heroes/Gwen.jpeg
    - assets/images/heroes/Helmar.jpeg
    - assets/images/heroes/Herne.jpeg
    - assets/images/heroes/Isstara.jpeg
    - assets/images/heroes/Kamil.jpeg
    - assets/images/heroes/Keera.jpeg
    - assets/images/heroes/Krusa.jpeg
    - assets/images/heroes/Lanasa.jpeg
    - assets/images/heroes/Lance.jpeg
    - assets/images/heroes/Lars.jpeg
    - assets/images/heroes/Logan.jpeg
    - assets/images/heroes/Lukin.jpeg
    - assets/images/heroes/Macleod.jpeg
    - assets/images/heroes/Mikazuki.jpeg
    - assets/images/heroes/Millicent.jpeg
    - assets/images/heroes/Neko.jpeg
    - assets/images/heroes/Nijuro.jpeg
    - assets/images/heroes/Olaf.jpeg
    - assets/images/heroes/Outis.jpeg
    - assets/images/heroes/Pentatonix.jpeg
    - assets/images/heroes/Petra.jpeg
    - assets/images/heroes/QueenKrita.jpeg
    - assets/images/heroes/Rhiannon.jpeg
    - assets/images/heroes/Rokara.jpeg
    - assets/images/heroes/Rosalin.jpeg
    - assets/images/heroes/Samael.jpeg
    - assets/images/heroes/Serra.jpeg
    - assets/images/heroes/Sola.jpeg
    - assets/images/heroes/Tara.jpeg
    - assets/images/heroes/Titania.jpeg
    - assets/images/heroes/Tristan.jpeg
    - assets/images/heroes/Ulfred.jpeg
    - assets/images/heroes/Urmas.jpeg
    - assets/images/heroes/Ursula.jpeg
    - assets/images/heroes/Viktor.jpeg
    - assets/images/heroes/Vordrai.jpeg
    - assets/images/heroes/WeiFeng.jpeg
    - assets/images/heroes/Wormwood.jpeg
    - assets/images/heroes/Zalam.jpeg
    - assets/images/heroes/Zoe.jpeg

  # Enemy types
    - assets/images/enemy_types/None_Diamond.png
    - assets/images/enemy_types/Beast_Diamond.png
    - assets/images/enemy_types/Cult_Diamond.png
    - assets/images/enemy_types/Demon_Diamond.png
    - assets/images/enemy_types/Goblin_Diamond.png
    - assets/images/enemy_types/Golem_Diamond.png
    - assets/images/enemy_types/Militia_Diamond.png
    - assets/images/enemy_types/Outlaw_Diamond.png
    - assets/images/enemy_types/Troll_Diamond.png
    - assets/images/enemy_types/Undead_Diamond.png

  # Effects
    - assets/images/effects/weaken.png
    - assets/images/effects/unfocus.png
    - assets/images/effects/stun.png
    - assets/images/effects/regenerate.png
    - assets/images/effects/protect.png
    - assets/images/effects/poison.png
    - assets/images/effects/fury.png
    - assets/images/effects/freeze.png
    - assets/images/effects/focus.png
    - assets/images/effects/expose.png
    - assets/images/effects/burn.png
    - assets/images/effects/acid.png

  # Icons
    - assets/images/icons/explore_transparent.png
    - assets/images/icons/swords_transparent.png
    - assets/images/icons/group_transparent.png
    - assets/images/icons/sword.png
    - assets/images/icons/axe.png
    - assets/images/icons/hammer.png

  # Backgrounds
    - assets/images/backgrounds/forge_background.jpg
    - assets/images/backgrounds/blue_background.jpg
    - assets/images/backgrounds/knight_banner.jpg
    - assets/images/backgrounds/guildhall_background.jpg
    - assets/images/backgrounds/study_background.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
